version: '3.8'
services:
  xray:
    image: teddysun/xray:latest
    container_name: homayoun
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/:/etc/xray/:ro
      - ./logs/:/var/log/xray/
