version: '3.8'
services:
  xray:
    image: teddysun/xray:latest
    container_name: moein_up
    restart: always
    ports:
      - 1313:1310
    volumes:
      - ./config/:/etc/xray/:ro
      - ./logs/:/var/log/xray/
