version: '3.8'
services:
  xray:
    image: teddysun/xray:latest
    container_name: moein_bridge
    restart: always
    ports:
      - 1210:1210
      - 1210:1210/udp
      - 1310:1310
    volumes:
      - ./config/:/etc/xray/:ro
      - ./logs/:/var/log/xray/
