version: '3.8'
services:
  xray:
    image: teddysun/xray:latest
    container_name: alieza
    restart: always
    network_mode: host
    volumes:
      - ./config/:/etc/xray/:ro
      - ./logs/:/var/log/xray/
      - /path/to/cert:/ssl/cert.pem
      - /path/to/key:/ssl/key.pem
